system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
system.enableActivityEagerExecution:
  - value: true
system.enableEagerWorkflowStart:
  - value: true
frontend.enableUpdateWorkflowExecution:
  - value: true
frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
frontend.workerVersioningWorkflowAPIs:
  - value: true
frontend.workerVersioningDataAPIs:
  - value: true
history.MaxBufferedQueryCount:
  - value: 100000
worker.buildIdScavengerEnabled:
    - value: true
worker.removableBuildIdDurationSinceDefault:
    - value: 1
system.enableNexus:
  - value: true
component.nexusoperations.callback.endpoint.template:
  - value: http://localhost:7243/namespaces/{{.NamespaceName}}/nexus/callback
component.callbacks.allowedAddresses:
  - value:
      - Pattern: "localhost:7243"
        AllowInsecure: true