version: '3.5'

services:
  cassandra:
    image: cassandra:3.11.9
    logging:
      driver: none
    ports:
      - "9042:9042"

  temporal:
    image: temporaliotest/auto-setup:sha-75e2009
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
      - "7239:7239"
      - "6933:6933"
      - "6934:6934"
      - "6935:6935"
      - "6939:6939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  unit-test-docker-jdk8:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile-JDK8
    environment:
      - "USER=unittest"
      - "TEMPORAL_SERVICE_ADDRESS=temporal:7233"
      - "USE_DOCKER_SERVICE=true"
    depends_on:
      - temporal
    volumes:
      - "../../:/temporal-java-client"

  unit-test-test-service-jdk18:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile-JDK18
    environment:
      - "USER=unittest"
      - "USE_DOCKER_SERVICE=false"
    volumes:
      - "../../:/temporal-java-client"

  jdk11:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile-JDK11
    environment:
      - "USER=unittest"
    volumes:
      - "../../:/temporal-java-client"

  jdk18:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile-JDK18
    environment:
      - "USER=unittest"
    volumes:
      - "../../:/temporal-java-client"